/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-02-24 02:27:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import org.apache.commons.lang.StringUtils;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t\t<title>会议室管理系统</title>\r\n");
      out.write("\t\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t\t<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("\t\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t\t<link href=\"css/login.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<SCRIPT type=text/javascript src=\"css/prototype.js\"></SCRIPT>\r\n");
      out.write("\t\t<LINK rel=stylesheet type=text/css href=\"css/index.css\">\r\n");
      out.write("\t\t<LINK rel=stylesheet type=text/css href=\"css/global.css\">\r\n");
      out.write("\t\t<SCRIPT type=text/javascript src=\"css/weaver.js\"></SCRIPT>\r\n");
      out.write("\t\t<SCRIPT type=text/javascript>\r\n");
      out.write("\t\t\t\tfunction validate() {\r\n");
      out.write("\t\t\t\tvar username = document.getElementById('username');\r\n");
      out.write("\t\t\t\tvar password = document.getElementById('password');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif (username.value == '') {\r\n");
      out.write("\t\t\t\t\talert('用户名为必填！');\r\n");
      out.write("\t\t\t\t\tusername.focus();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\tif (password.value == '') {\r\n");
      out.write("\t\t\t\t\talert('密码为必填!');\r\n");
      out.write("\t\t\t\t\tpassword.focus();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t</SCRIPT>\r\n");
      out.write("\t\t<STYLE type=text/css>.login_sub {\r\n");
      out.write("\t\t\tBORDER-BOTTOM: 0px; BORDER-LEFT: 0px; WIDTH: 77px; BACKGROUND: url(images/login_02.gif) no-repeat; HEIGHT: 33px; COLOR: #060652; FONT-SIZE: 14px; BORDER-TOP: 0px; FONT-WEIGHT: bold; BORDER-RIGHT: 0px\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.login_res {\r\n");
      out.write("\t\t\tBORDER-BOTTOM: 0px; BORDER-LEFT: 0px; WIDTH: 77px; BACKGROUND: url(images/reset.gif) no-repeat; HEIGHT: 33px; COLOR: #060652; FONT-SIZE: 14px; BORDER-TOP: 0px; FONT-WEIGHT: bold; BORDER-RIGHT: 0px\r\n");
      out.write("\t\t}\r\n");
      out.write("   \r\n");
      out.write("<!--\r\n");
      out.write(".STYLE1 {font-size: 14px}\r\n");
      out.write("-->\r\n");
      out.write("        </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<DIV id=login>\r\n");
      out.write("\t\t\t<DIV class=logo><img src=\"images/logo2.gif\" width=\"252\" height=\"31\"></DIV>\r\n");
      out.write("\t\t\t<DIV class=line></DIV>\r\n");
      out.write("\t\t\t<DIV class=\"clearfix first\">\r\n");
      out.write("\t\t\t\t<form id=\"loginForm\"\r\n");
      out.write("\t\t\taction=\"");
      out.print(request.getContextPath());
      out.write("/user_login.do\"\r\n");
      out.write("\t\t\tonsubmit=\"return validate();\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<DIV>\r\n");
      out.write("\t\t\t\t\t\t<IMG src=\"images/login_bg.jpg\" width=\"567\" height=\"329\" style=\"WIDTH: 450px; HEIGHT: 230px\">\t\t\t\t\t</DIV>\r\n");
      out.write("\t\t\t\t  <DIV class=login>\r\n");
      out.write("\t\t\t\t\t<H2>\r\n");
      out.write("\t\t\t\t\t\t\t系统登录\r\n");
      out.write("\t\t\t\t\t</H2>\r\n");
      out.write("\t\t\t\t\t\t<DIV class=bd>\r\n");
      out.write("\t\t\t\t\t\t  <TABLE border=0 cellSpacing=0 cellPadding=0 width=300>\r\n");
      out.write("\t\t\t\t\t\t\t<TBODY>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD style=\"HEIGHT: 20px\">&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"MARGIN-TOP: 0px; HEIGHT: 20px; FONT-SIZE: 9pt; FONT-WEIGHT: normal; PADDING-TOP: 20px\">&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t用户名：\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"username\" name=\"user.loginName\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"input\" size=\"15\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<BR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t密&nbsp;&nbsp;码：\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" id=\"password\" name=\"user.password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"input\" size=\"15\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<BR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD class=forget>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TR style=\"PADDING-BOTTOM: 10px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<INPUT style=\"CURSOR: hand\" class=login_sub type=submit\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=button value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<INPUT style=\"CURSOR: hand\" class=login_res type=reset\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=button value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t</TBODY>\r\n");
      out.write("\t\t\t\t\t\t  </TABLE>\r\n");
      out.write("\t\t\t\t\t\t</DIV>\r\n");
      out.write("\t\t\t\t\t</DIV>\r\n");
      out.write("\t\t\t\t</FORM>\r\n");
      out.write("\t\t\t</DIV>\r\n");
      out.write("\t\t\t<SPAN\r\n");
      out.write("\t\t\t\tstyle=\"TEXT-ALIGN: left; PADDING-BOTTOM: 0px; LINE-HEIGHT: 25px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; COLOR: #696969; PADDING-TOP: 0px\">提示：<BR>&nbsp;&nbsp;&nbsp;&nbsp;<IMG\r\n");
      out.write("\t\t\t\t\tstyle=\"WIDTH: 9px\" src=\"images/point1.jpg\">&nbsp;本系统需要运行在<FONT\r\n");
      out.write("\t\t\t\tstyle=\"COLOR: #003d76\">IE7.0</FONT>及以上版本，推荐浏览的分辨率：<FONT\r\n");
      out.write("\t\t\t\tstyle=\"COLOR: #003d76\">1280*800</FONT> <BR>&nbsp;&nbsp;&nbsp;&nbsp;<IMG\r\n");
      out.write("\t\t\t\t\tstyle=\"WIDTH: 9px\" src=\"images/point1.jpg\">&nbsp;登录前请将本页面地址加入<FONT\r\n");
      out.write("\t\t\t\tstyle=\"COLOR: #003d76\">IE可信站点</FONT>，并把安全级别调成低 </SPAN>\r\n");
      out.write("\t\t\t<BR>\r\n");
      out.write("\t\t\t<BR>\r\n");
      out.write("\t\t\t<DIV class=bottom>\r\n");
      out.write("\t\t\t\t<DIV class=copy>\r\n");
      out.write("\t\t\t\t\t版权所有&copy;2010 大连万达集团股份有限公司\r\n");
      out.write("\t\t\t\t</DIV>\r\n");
      out.write("\t\t\t</DIV>\r\n");
      out.write("\t\t</DIV>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
