/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-05-07 08:55:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.tempmenu.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SP_005f2016111813580001_run extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("﻿<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,Chrome=1\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=9\" />\r\n");
      out.write("    <title>万达员工餐厅</title>\r\n");
      out.write("    <!-- basic styles -->\r\n");
      out.write("    <link href=\"../../css/bootstrap.min.css?v=1.001\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"../../assets/css/bootstrap.min.css?v=1.001\" rel=\"stylesheet\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../assets/css/font-awesome.min.css?v=1.001\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../css/font-awesome.min.css?v=1.003\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../css/font-awesome.min.ace.css?v=1.001\">\r\n");
      out.write("\t<!--[if IE 7]>\r\n");
      out.write("\t<link rel=\" stylesheet\" href=\"../../assets/css/font-awesome-ie7.min.css\" />\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\t<!-- ace styles -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../../assets/css/ace.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../../assets/css/ace-rtl.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../../assets/css/ace-skins.min.css\" />\r\n");
      out.write("\t<!--[if lte IE 8]>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"../../assets/css/ace-ie.min.css\" />\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("    <!-- inline styles related to this page -->\r\n");
      out.write("    <!-- 自定义样式 -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../../css/jquery-webox.css?ver=1.00\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../css/contenttable.css?ver=1.004\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../css/wdmenu.css?ver=1.015\" />\r\n");
      out.write("    <!-- 全局js -->\r\n");
      out.write("    <script src=\"../../js/jquery.min.js?v=1.11.1\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"../../js/bootstrap.min.js?v=3.3.6\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"../../js/plugins/metisMenu/jquery.metisMenu.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <!--<script src=\"../../js/plugins/slimscroll/jquery.slimscroll.min.js\" type=\"text/javascript\"></script>-->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../js/jquery-webox.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <!-- 自定义js -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../js/wdmenu.js?v=1.009\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../js/jquery-webox.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../js/common.js?ver=1.4\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../js/contabs.js?ver=1.03\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../js/menu.js?ver=1.04\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../js/frame.js?ver=1.01\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"\">\r\n");
      out.write("    <div class=\"navbar navbar-default\" id=\"header\">\r\n");
      out.write("        <div class=\"navbar-container\" id=\"navbar-container\">\r\n");
      out.write("            <div class=\"navbar-header pull-left\">\r\n");
      out.write("                <a href=\"#\" class=\"navbar-brand\">\r\n");
      out.write("                    <small>\r\n");
      out.write("                        <i class=\"{titlepic}\"></i>\r\n");
      out.write("                        万达员工餐厅\r\n");
      out.write("                    </small>\r\n");
      out.write("                </a>\r\n");
      out.write("                <!--\r\n");
      out.write("                <div class=\"headerTop\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"../../logout\"><i class=\"fa fa fa-sign-out\"></i> 退出</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">管理员</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>-->\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"navbar-header pull-right\" role=\"navigation\">\r\n");
      out.write("                <ul class=\"nav ace-nav\">\r\n");
      out.write("                    <li class=\"light-blue\">\r\n");
      out.write("                        <a data-toggle=\"dropdown\" href=\"#\" class=\"dropdown-toggle\">\r\n");
      out.write("                            <img class=\"nav-user-photo\" src=\"../../assets/avatars/user.jpg\" alt=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope._user.realname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'s Photo\">\r\n");
      out.write("                            <span class=\"user-info\">\r\n");
      out.write("                                <small>欢迎光临,</small>\r\n");
      out.write("                                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope._user.realname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\r\n");
      out.write("                            <i class=\"icon-caret-down\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("\r\n");
      out.write("                        <ul class=\"user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\" onclick=\"openWin(700,300,'编辑个人资料','../form/SF_201503180002.form?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope._user.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',null,null);\">\r\n");
      out.write("                                    <i class=\"icon-user\"></i>\r\n");
      out.write("                                    个人资料\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"divider\"></li>\r\n");
      out.write("\r\n");
      out.write("                            <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"../../logout\"><i class=\"icon-off\"></i> 退出</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul><!-- /.ace-nav -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.navbar-header -->\r\n");
      out.write("        </div><!-- /.container -->\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main-container\" id=\"main-container\">\r\n");
      out.write("        <div class=\"main-container-inner\">\r\n");
      out.write("            <a class=\"menu-toggler\" id=\"menu-toggler\" href=\"#\">\r\n");
      out.write("                <span class=\"menu-text\"></span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"sidebar\" id=\"sidebar\">\r\n");
      out.write("                <!-- nav-list -->\r\n");
      out.write("                <ul id=\"side-menu\" class=\"nav nav-list\">\r\n");
      out.write("                    ");
      if (_jspx_meth_shiro_005fhasPermission_005f0(_jspx_page_context))
        return;
      if (_jspx_meth_shiro_005fhasPermission_005f13(_jspx_page_context))
        return;
      if (_jspx_meth_shiro_005fhasPermission_005f15(_jspx_page_context))
        return;
      out.write("</ul>\r\n");
      out.write("                <!-- /.nav-list -->\r\n");
      out.write("                <div class=\"sidebar-collapse\" id=\"sidebar-collapse\">\r\n");
      out.write("                    <i class=\"glyphicon glyphicon-circle-arrow-left navbar-minimalize\" data-icon1=\"glyphicon glyphicon-circle-arrow-left\" data-icon2=\"glyphicon glyphicon-circle-arrow-right\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- main-content -->\r\n");
      out.write("            <div class=\"main-content\">\r\n");
      out.write("                <div class=\"breadcrumbs content-tabs\">\r\n");
      out.write("                    <button class=\"roll-nav roll-left J_tabLeft\">\r\n");
      out.write("                        <i class=\"fa fa-backward\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <nav class=\"page-tabs J_menuTabs\">\r\n");
      out.write("                        <div class=\"page-tabs-content\">\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("</div>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                    <button class=\"roll-nav roll-right J_tabRight\">\r\n");
      out.write("                        <i class=\"fa fa-forward\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"btn-group roll-nav roll-right J_tabExit\">\r\n");
      out.write("                        <button class=\"dropdown J_tabClose\" data-toggle=\"dropdown\">\r\n");
      out.write("                            关闭操作<span class=\"caret\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <ul role=\"menu\" class=\"dropdown-menu dropdown-menu-right UL_tabClose\">\r\n");
      out.write("                            <li class=\"J_tabShowActive\">\r\n");
      out.write("                                <a>定位当前选项卡</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"divider\"></li>\r\n");
      out.write("                            <li class=\"J_tabCloseAll\">\r\n");
      out.write("                                <a>关闭全部选项卡</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"J_tabCloseOther\">\r\n");
      out.write("                                <a>关闭其他选项卡</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"page-content J_mainContent\" id=\"content-main\">\r\n");
      out.write("                    <iframe class=\"J_iframe\" name=\"iframe0\" width=\"100%\" height=\"100%\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.rootUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" frameborder=\"0\" data-id=\"index_v1\" onload=\"fn_changeFrameHeight(this);\" scrolling=\"no\" seamless></iframe>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.main-content -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f0 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f0.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f0.setParent(null);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(111,20) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f0.setName("menuinfo201611250001");
    int _jspx_eval_shiro_005fhasPermission_005f0 = _jspx_th_shiro_005fhasPermission_005f0.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li class=\"active\"><a href=\"#\"><i class=\"fa fa-tasks\"></i><span class=\"nav-label menu-text\"> 餐厅配置</span><b class=\"arrow icon-angle-down\"></b></a><ul class=\"submenu nav nav-second-level collapse in\" parentkey=\"-1\" key=\"menuinfo201611250001\">");
        if (_jspx_meth_shiro_005fhasPermission_005f1(_jspx_th_shiro_005fhasPermission_005f0, _jspx_page_context))
          return true;
        if (_jspx_meth_shiro_005fhasPermission_005f5(_jspx_th_shiro_005fhasPermission_005f0, _jspx_page_context))
          return true;
        if (_jspx_meth_shiro_005fhasPermission_005f8(_jspx_th_shiro_005fhasPermission_005f0, _jspx_page_context))
          return true;
        out.write("</ul>\r\n");
        out.write("</li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f0);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f1 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f1.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f0);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(112,240) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f1.setName("SMB_2018040314440001");
    int _jspx_eval_shiro_005fhasPermission_005f1 = _jspx_th_shiro_005fhasPermission_005f1.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li class=\"active menuactive\"><a href=\"#\"><i class=\"icon-double-angle-right\"></i><i class=\"fa fa-edit\"></i><span class=\"nav-label menu-text\"> 组织扩展管理</span><b class=\"arrow icon-angle-down\"></b></a><ul class=\"submenu nav nav-third-level collapse in\" parentkey=\"menuinfo201611250001\" key=\"SMB_2018040314440001\">");
        if (_jspx_meth_shiro_005fhasPermission_005f2(_jspx_th_shiro_005fhasPermission_005f1, _jspx_page_context))
          return true;
        if (_jspx_meth_shiro_005fhasPermission_005f3(_jspx_th_shiro_005fhasPermission_005f1, _jspx_page_context))
          return true;
        if (_jspx_meth_shiro_005fhasPermission_005f4(_jspx_th_shiro_005fhasPermission_005f1, _jspx_page_context))
          return true;
        out.write("</ul>\r\n");
        out.write("</li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f1);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f2 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f2.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f1);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(113,308) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f2.setName("SMB_2018041013240001");
    int _jspx_eval_shiro_005fhasPermission_005f2 = _jspx_th_shiro_005fhasPermission_005f2.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li class=\"active menuactive\"><a class=\"J_menuItem\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/platform/tool/ST_201503180001.tool\"><i class=\"fa fa-asterisk\"></i><span class=\"nav-label menu-text\"> 用户管理</span></a></li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f2);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f3 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f3.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f1);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(116,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f3.setName("SMB_2018041017550001");
    int _jspx_eval_shiro_005fhasPermission_005f3 = _jspx_th_shiro_005fhasPermission_005f3.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a class=\"J_menuItem\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/platform/tree/sc_organization.treelist\"><i class=\"fa fa-asterisk\"></i><span class=\"nav-label menu-text\"> 组织机构管理</span></a></li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f3);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f4 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f4.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f1);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(119,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f4.setName("SMB_2018040314450018");
    int _jspx_eval_shiro_005fhasPermission_005f4 = _jspx_th_shiro_005fhasPermission_005f4.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a class=\"J_menuItem\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/platform/tree/SE_2018040214550001.treelist\"><i class=\"fa fa-asterisk\"></i><span class=\"nav-label menu-text\"> 组织扩展管理</span></a></li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f4);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f5 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f5.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f0);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(125,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f5.setName("menuinfo201611250002");
    int _jspx_eval_shiro_005fhasPermission_005f5 = _jspx_th_shiro_005fhasPermission_005f5.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a href=\"#\"><i class=\"icon-double-angle-right\"></i><i class=\"fa fa-edit\"></i><span class=\"nav-label menu-text\"> 员工卡管理</span><b class=\"arrow icon-angle-down\"></b></a><ul class=\"submenu nav nav-third-level collapse \" parentkey=\"menuinfo201611250001\" key=\"menuinfo201611250002\">");
        if (_jspx_meth_shiro_005fhasPermission_005f6(_jspx_th_shiro_005fhasPermission_005f5, _jspx_page_context))
          return true;
        if (_jspx_meth_shiro_005fhasPermission_005f7(_jspx_th_shiro_005fhasPermission_005f5, _jspx_page_context))
          return true;
        out.write("</ul>\r\n");
        out.write("</li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f5.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f5);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f5, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f6 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f6.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f5);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(126,279) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f6.setName("SMB_2018011014540001");
    int _jspx_eval_shiro_005fhasPermission_005f6 = _jspx_th_shiro_005fhasPermission_005f6.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a class=\"J_menuItem\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/platform/query/SQ_2018011014490001.query\"><i class=\"fa fa-asterisk\"></i><span class=\"nav-label menu-text\"> 时间段列表</span></a></li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f6.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f6);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f5, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f7 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f7.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f5);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(129,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f7.setName("menuinfo201611250003");
    int _jspx_eval_shiro_005fhasPermission_005f7 = _jspx_th_shiro_005fhasPermission_005f7.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a class=\"J_menuItem\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/platform/tree/SE_2016112111180001.treelist\"><i class=\"fa fa-asterisk\"></i><span class=\"nav-label menu-text\"> 餐厅部门配置</span></a></li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f7.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f7);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f8 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f8.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f0);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(135,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f8.setName("SMB_2018031610090001");
    int _jspx_eval_shiro_005fhasPermission_005f8 = _jspx_th_shiro_005fhasPermission_005f8.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a href=\"#\"><i class=\"icon-double-angle-right\"></i><i class=\"fa fa-edit\"></i><span class=\"nav-label menu-text\"> 联营卡管理</span><b class=\"arrow icon-angle-down\"></b></a><ul class=\"submenu nav nav-third-level collapse \" parentkey=\"menuinfo201611250001\" key=\"SMB_2018031610090001\">");
        if (_jspx_meth_shiro_005fhasPermission_005f9(_jspx_th_shiro_005fhasPermission_005f8, _jspx_page_context))
          return true;
        if (_jspx_meth_shiro_005fhasPermission_005f10(_jspx_th_shiro_005fhasPermission_005f8, _jspx_page_context))
          return true;
        if (_jspx_meth_shiro_005fhasPermission_005f11(_jspx_th_shiro_005fhasPermission_005f8, _jspx_page_context))
          return true;
        if (_jspx_meth_shiro_005fhasPermission_005f12(_jspx_th_shiro_005fhasPermission_005f8, _jspx_page_context))
          return true;
        out.write("</ul>\r\n");
        out.write("</li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f8.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f8);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f8, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f9 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f9.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f8);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(136,279) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f9.setName("SMB_2018031610100025");
    int _jspx_eval_shiro_005fhasPermission_005f9 = _jspx_th_shiro_005fhasPermission_005f9.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a class=\"J_menuItem\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/platform/changeurl?urlInfo=http%3A%2F%2Flocalhost%3A8087%2FWristStrap%2F2010_bracelet_type%2F00_standard.do\"><i class=\"fa fa-asterisk\"></i><span class=\"nav-label menu-text\"> 卡类型管理</span></a></li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f9.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f9);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f9);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f8, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f10 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f10.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f8);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(139,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f10.setName("SMB_2018031916330014");
    int _jspx_eval_shiro_005fhasPermission_005f10 = _jspx_th_shiro_005fhasPermission_005f10.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f10 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a class=\"J_menuItem\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/platform/changeurl?urlInfo=http%3A%2F%2Flocalhost%3A8087%2FWristStrap%2F2030_bracelet_info%2F2030_standard.do\"><i class=\"fa fa-asterisk\"></i><span class=\"nav-label menu-text\"> 卡信息管理</span></a></li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f10.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f10);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f10);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f11(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f8, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f11 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f11.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f8);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(142,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f11.setName("SMB_2018031916350015");
    int _jspx_eval_shiro_005fhasPermission_005f11 = _jspx_th_shiro_005fhasPermission_005f11.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f11 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a class=\"J_menuItem\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/platform/changeurl?urlInfo=http%3A%2F%2Flocalhost%3A8087%2FWristStrap%2F5020_consume_info%2F5020_standard.do\"><i class=\"fa fa-asterisk\"></i><span class=\"nav-label menu-text\"> 卡押金调整</span></a></li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f11.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f11);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f11);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f12(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f8, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f12 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f12.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f12.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f8);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(145,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f12.setName("SMB_2018031916380001");
    int _jspx_eval_shiro_005fhasPermission_005f12 = _jspx_th_shiro_005fhasPermission_005f12.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f12 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a class=\"J_menuItem\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/platform/changeurl?urlInfo=http%3A%2F%2Flocalhost%3A8087%2FWristStrap%2F1020_tcounter%2F1020_standard.do\"><i class=\"fa fa-asterisk\"></i><span class=\"nav-label menu-text\"> POS机管理</span></a></li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f12.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f12);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f12);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f13 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f13.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f13.setParent(null);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(154,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f13.setName("SMB_2017121123170001");
    int _jspx_eval_shiro_005fhasPermission_005f13 = _jspx_th_shiro_005fhasPermission_005f13.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f13 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a href=\"#\"><i class=\"fa fa-tasks\"></i><span class=\"nav-label menu-text\"> 员工报餐管理</span><b class=\"arrow icon-angle-down\"></b></a><ul class=\"submenu nav nav-second-level collapse \" parentkey=\"-1\" key=\"SMB_2017121123170001\">");
        if (_jspx_meth_shiro_005fhasPermission_005f14(_jspx_th_shiro_005fhasPermission_005f13, _jspx_page_context))
          return true;
        out.write("</ul>\r\n");
        out.write("</li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f13.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f13);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f13);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f14(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f13, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f14 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f14.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f14.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f13);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(155,225) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f14.setName("SMB_2017121123170011");
    int _jspx_eval_shiro_005fhasPermission_005f14 = _jspx_th_shiro_005fhasPermission_005f14.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f14 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a class=\"J_menuItem\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/platform/tool/ST_2017121313120001.tool\"><i class=\"icon-double-angle-right\"></i><i class=\"fa fa-edit\"></i><span class=\"nav-label menu-text\"> 部门报餐申请</span></a></li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f14.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f14);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f14);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f15(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f15 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f15.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f15.setParent(null);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(161,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f15.setName("menuinfo201611250004");
    int _jspx_eval_shiro_005fhasPermission_005f15 = _jspx_th_shiro_005fhasPermission_005f15.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f15 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a href=\"#\"><i class=\"fa fa-tasks\"></i><span class=\"nav-label menu-text\"> 餐厅报表</span><b class=\"arrow icon-angle-down\"></b></a><ul class=\"submenu nav nav-second-level collapse \" parentkey=\"-1\" key=\"menuinfo201611250004\">");
        if (_jspx_meth_shiro_005fhasPermission_005f16(_jspx_th_shiro_005fhasPermission_005f15, _jspx_page_context))
          return true;
        if (_jspx_meth_shiro_005fhasPermission_005f20(_jspx_th_shiro_005fhasPermission_005f15, _jspx_page_context))
          return true;
        out.write("</ul>\r\n");
        out.write("</li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f15.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f15);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f15);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f16(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f15, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f16 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f16.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f16.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f15);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(162,223) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f16.setName("menuinfo201611250005");
    int _jspx_eval_shiro_005fhasPermission_005f16 = _jspx_th_shiro_005fhasPermission_005f16.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f16 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a href=\"#\"><i class=\"icon-double-angle-right\"></i><i class=\"fa fa-edit\"></i><span class=\"nav-label menu-text\"> 员工餐厅报表</span><b class=\"arrow icon-angle-down\"></b></a><ul class=\"submenu nav nav-third-level collapse \" parentkey=\"menuinfo201611250004\" key=\"menuinfo201611250005\">");
        if (_jspx_meth_shiro_005fhasPermission_005f17(_jspx_th_shiro_005fhasPermission_005f16, _jspx_page_context))
          return true;
        if (_jspx_meth_shiro_005fhasPermission_005f18(_jspx_th_shiro_005fhasPermission_005f16, _jspx_page_context))
          return true;
        if (_jspx_meth_shiro_005fhasPermission_005f19(_jspx_th_shiro_005fhasPermission_005f16, _jspx_page_context))
          return true;
        out.write("</ul>\r\n");
        out.write("</li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f16.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f16);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f16);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f17(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f16, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f17 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f17.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f17.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f16);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(163,280) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f17.setName("SMB_2018032317000001");
    int _jspx_eval_shiro_005fhasPermission_005f17 = _jspx_th_shiro_005fhasPermission_005f17.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f17 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a class=\"J_menuItem\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/platform/query/SQ_2018032316140001.query\"><i class=\"fa fa-asterisk\"></i><span class=\"nav-label menu-text\"> 用餐超次统计表</span></a></li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f17.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f17.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f17);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f17);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f18(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f16, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f18 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f18.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f18.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f16);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(166,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f18.setName("SMB_2018011114100001");
    int _jspx_eval_shiro_005fhasPermission_005f18 = _jspx_th_shiro_005fhasPermission_005f18.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f18 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a class=\"J_menuItem\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/platform/tool/ST_2018011114050001.tool\"><i class=\"fa fa-asterisk\"></i><span class=\"nav-label menu-text\"> 当月就餐报表(员工)</span></a></li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f18.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f18.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f18);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f18);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f19(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f16, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f19 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f19.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f19.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f16);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(169,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f19.setName("SMB_2018011114110014");
    int _jspx_eval_shiro_005fhasPermission_005f19 = _jspx_th_shiro_005fhasPermission_005f19.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f19 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a class=\"J_menuItem\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/platform/tool/ST_2018011114050002.tool\"><i class=\"fa fa-asterisk\"></i><span class=\"nav-label menu-text\"> 历史就餐报表(员工)</span></a></li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f19.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f19.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f19);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f19);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f20(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f15, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f20 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f20.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f20.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f15);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(175,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f20.setName("SMB_2018040315370001");
    int _jspx_eval_shiro_005fhasPermission_005f20 = _jspx_th_shiro_005fhasPermission_005f20.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f20 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a href=\"#\"><i class=\"icon-double-angle-right\"></i><i class=\"fa fa-edit\"></i><span class=\"nav-label menu-text\"> 联营卡报表</span><b class=\"arrow icon-angle-down\"></b></a><ul class=\"submenu nav nav-third-level collapse \" parentkey=\"menuinfo201611250004\" key=\"SMB_2018040315370001\">");
        if (_jspx_meth_shiro_005fhasPermission_005f21(_jspx_th_shiro_005fhasPermission_005f20, _jspx_page_context))
          return true;
        if (_jspx_meth_shiro_005fhasPermission_005f22(_jspx_th_shiro_005fhasPermission_005f20, _jspx_page_context))
          return true;
        if (_jspx_meth_shiro_005fhasPermission_005f23(_jspx_th_shiro_005fhasPermission_005f20, _jspx_page_context))
          return true;
        if (_jspx_meth_shiro_005fhasPermission_005f24(_jspx_th_shiro_005fhasPermission_005f20, _jspx_page_context))
          return true;
        out.write("</ul>\r\n");
        out.write("</li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f20.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f20.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f20);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f20);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f21(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f20, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f21 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f21.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f21.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f20);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(176,279) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f21.setName("SMB_2018040315370021");
    int _jspx_eval_shiro_005fhasPermission_005f21 = _jspx_th_shiro_005fhasPermission_005f21.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f21 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a class=\"J_menuItem\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/platform/tool/ST_2018040315400001.tool\"><i class=\"fa fa-asterisk\"></i><span class=\"nav-label menu-text\"> 当月就餐报表(联营)</span></a></li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f21.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f21.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f21);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f21);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f22(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f20, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f22 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f22.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f22.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f20);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(179,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f22.setName("SMB_2018040315380021");
    int _jspx_eval_shiro_005fhasPermission_005f22 = _jspx_th_shiro_005fhasPermission_005f22.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f22 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a class=\"J_menuItem\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/platform/tool/ST_2018040315400002.tool\"><i class=\"fa fa-asterisk\"></i><span class=\"nav-label menu-text\"> 历史就餐报表(联营)</span></a></li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f22.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f22.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f22);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f22);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f23(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f20, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f23 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f23.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f23.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f20);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(182,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f23.setName("SMB_2018040811440001");
    int _jspx_eval_shiro_005fhasPermission_005f23 = _jspx_th_shiro_005fhasPermission_005f23.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f23 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a class=\"J_menuItem\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/platform/query/SQ_2018040318000001.query\"><i class=\"fa fa-asterisk\"></i><span class=\"nav-label menu-text\"> 联营卡充值表</span></a></li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f23.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f23.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f23);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f23);
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f24(javax.servlet.jsp.tagext.JspTag _jspx_th_shiro_005fhasPermission_005f20, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f24 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    _jspx_th_shiro_005fhasPermission_005f24.setPageContext(_jspx_page_context);
    _jspx_th_shiro_005fhasPermission_005f24.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_shiro_005fhasPermission_005f20);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(185,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_shiro_005fhasPermission_005f24.setName("SMB_2018040811490001");
    int _jspx_eval_shiro_005fhasPermission_005f24 = _jspx_th_shiro_005fhasPermission_005f24.doStartTag();
    if (_jspx_eval_shiro_005fhasPermission_005f24 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<li><a class=\"J_menuItem\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/platform/query/SQ_2018040318010001.query\"><i class=\"fa fa-asterisk\"></i><span class=\"nav-label menu-text\"> 联营卡消费报表</span></a></li>\r\n");
        int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f24.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_shiro_005fhasPermission_005f24.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f24);
      return true;
    }
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f24);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/tempmenu/page/SP_2016111813580001.run(209,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.hasRoot==1 && requestScope.rootUrl !=''}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<a href=\"javascript:;\" class=\"active J_menuTab\" data-id=\"index_v1\">首页</a>\r\n");
        out.write("                            ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
