/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-03-27 07:53:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.tree;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class commontree_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=8,chrome=1\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../../css/tree.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../../css/jquery-webox.css\" />\r\n");
      out.write("<link href=\"../../assets/css/bootstrap.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("<link href=\"../../css/style.css?v=4.1.0\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"../../assets/img/favicon.png\" type=\"image/x-icon\">\r\n");
      out.write("<!--Basic Styles-->\r\n");
      out.write("<link id=\"bootstrap-rtl-link\" href=\"\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../assets/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../assets/css/weather-icons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<!--Fonts-->\r\n");
      out.write("<link href=\"../../css/usesofont.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<!--Beyond styles-->\r\n");
      out.write("<link href=\"../../assets/css/demo.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../assets/css/typicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../assets/css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../css/tree.css\" rel=\"stylesheet\">\r\n");
      out.write("<link id=\"skin-link\" href=\"\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../js/jquery-webox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../js/jquery.url.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../js/common.js?ver=1.4\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../js/plugins/slimscroll/jquery.slimscroll.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../js/treemain.js?ver=1.02\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../js/frame.js?ver=1.01\"></script>\r\n");
      out.write("<title>通用树</title>\r\n");
      out.write("</head>\r\n");
      out.write("<!-- onload=\"initTreeMain('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope._viewpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\" -->\r\n");
      out.write("<body onload=\"initTreeMain('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope._viewpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\">\r\n");
      out.write("\t<table border=\"0\" width=\"100%\" height=\"100%\" cellspacing=\"0\"\r\n");
      out.write("\t\tcellpadding=\"0\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"vertical-align:top;\">\r\n");
      out.write("            <iframe id=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope._viewpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("_frameleft\" \r\n");
      out.write("\t\t\t\t\tstyle=\"BORDER-RIGHT: buttonface 1px dashed;height:100%;\" name=\"Tree\"\r\n");
      out.write("\t\t\t\t\tframeborder=\"0\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope._urlInfo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" scrolling=\"auto\"\r\n");
      out.write("\t\t\t\t\t></iframe>\r\n");
      out.write("            </td>\r\n");
      out.write("\t\t\t<td width=\"2px\"></td>\r\n");
      out.write("\t\t\t<td style=\"vertical-align:top;text-align:left;\">\r\n");
      out.write("            \t<iframe id=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope._viewpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("_Main\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope._viewpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("_Main\" frameborder=\"0\" src=\"../tree/empty\"\r\n");
      out.write("\t\t\t\t\tscrolling=\"auto\" style=\"width:100%;height:100%;\"></iframe>\r\n");
      out.write("            </td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
